version: '3.7'
services:
  events-app:
    image: supradeux/events-app:latest
    ports: 
      - "3000:3000"
      - "8080:8080"
    environment:
      - JAEGER_ENDPOINT=http://docker.for.mac.localhost:14268/api/traces
    networks:
      - jaeger-example

networks:
  jaeger-example:
