apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: events-app
  name: events-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: events-app
    spec:
      containers:
      - image: docker.io/supradeux/events-app
        name: events-app
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: events-app
  labels:
    run: events-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: events-app
  type: NodePort